
import classes.Appointment;
import classes.Centre;
import classes.GeneralFunction;
import classes.People;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Asus
 */
public class PersonnelPeople extends javax.swing.JFrame {

    Color priColor = new Color(0, 109, 119);
    Color secColor = new Color(131, 197, 190);
    Color bgColor = new Color(237, 246, 249);

    GeneralFunction gf = new GeneralFunction();
    Appointment ap = new Appointment();
    People ppl = new People();
    Centre c = new Centre();
    ArrayList<ArrayList<String>> appointmentList, centreList, peopleList;
    JFrame PersonnelPeople = this;

    public PersonnelPeople() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/vaccine-logo.png")));

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                String ObjButtons[] = { "Yes", "No" };
                int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to exit?", "Vaccineo",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    Login log = new Login();
                    log.setVisible(true);
                    PersonnelPeople.setVisible(false);
                }
            }
        });
    }

    public PersonnelPeople(String id) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/vaccine-logo.png")));
        pplId.setText(id);
        ppl.setId(id);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                String ObjButtons[] = { "Yes", "No" };
                int PromptResult = JOptionPane.showOptionDialog(null, "Are you sure you want to exit?", "Vaccineo",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, ObjButtons, ObjButtons[1]);
                if (PromptResult == JOptionPane.YES_OPTION) {
                    Login log = new Login();
                    log.setVisible(true);
                    PersonnelPeople.setVisible(false);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dbPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ppPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cnPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vaPanel = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        pplName = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(60, secColor);
        pplCategory = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(60, secColor);
        vacStatus = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pplAddress = new javax.swing.JLabel();
        pplAge = new javax.swing.JLabel();
        pplGender = new javax.swing.JLabel();
        pplDOB = new javax.swing.JLabel();
        pplId = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        firstDosePanel = new RoundedPanel(10, secColor);
        firstDoseLbl = new javax.swing.JLabel();
        firstDoseLocation = new javax.swing.JLabel();
        firstDoseDate = new javax.swing.JLabel();
        firstDoseVacPanel = new javax.swing.JPanel();
        firstDoseVac = new javax.swing.JLabel();
        firstDoseDone = new javax.swing.JLabel();
        backBtn = new RoundedPanel(10, priColor);
        jLabel33 = new javax.swing.JLabel();
        editPeopleInfo = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        secDosePanel = new RoundedPanel(10, secColor);
        secDoseLbl = new javax.swing.JLabel();
        secDoseLocation = new javax.swing.JLabel();
        secDoseDate = new javax.swing.JLabel();
        secDoseVacPanel = new javax.swing.JPanel();
        secDoseVac = new javax.swing.JLabel();
        secDoseDone = new javax.swing.JLabel();
        scheduleAppointment = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        registerVaccination = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        formBackground.setBackground(new java.awt.Color(237, 246, 249));
        formBackground.setMaximumSize(new java.awt.Dimension(1440, 800));
        formBackground.setPreferredSize(new java.awt.Dimension(1440, 800));

        jPanel1.setBackground(new java.awt.Color(0, 109, 119));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccineo-logo-big.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(154, 41));
        jLabel1.setMinimumSize(new java.awt.Dimension(154, 41));

        dbPanel.setBackground(new java.awt.Color(0, 109, 119));
        dbPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dbPanel.setPreferredSize(new java.awt.Dimension(300, 65));
        dbPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbPanelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbPanelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard-icon.png"))); // NOI18N

        javax.swing.GroupLayout dbPanelLayout = new javax.swing.GroupLayout(dbPanel);
        dbPanel.setLayout(dbPanelLayout);
        dbPanelLayout.setHorizontalGroup(
                dbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dbPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        dbPanelLayout.setVerticalGroup(
                dbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dbPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(dbPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                .addContainerGap(23, Short.MAX_VALUE)));

        logoutPanel.setBackground(new java.awt.Color(131, 197, 190));
        logoutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logout");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-logo.png"))); // NOI18N

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
                logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(logoutPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        logoutPanelLayout.setVerticalGroup(
                logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(logoutPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(
                                        logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(22, Short.MAX_VALUE)));

        ppPanel.setBackground(new java.awt.Color(131, 197, 190));
        ppPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ppPanel.setPreferredSize(new java.awt.Dimension(300, 65));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("People");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people-icon.png"))); // NOI18N

        javax.swing.GroupLayout ppPanelLayout = new javax.swing.GroupLayout(ppPanel);
        ppPanel.setLayout(ppPanelLayout);
        ppPanelLayout.setHorizontalGroup(
                ppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        ppPanelLayout.setVerticalGroup(
                ppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(ppPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                .addContainerGap(23, Short.MAX_VALUE)));

        cnPanel.setBackground(new java.awt.Color(0, 109, 119));
        cnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cnPanel.setPreferredSize(new java.awt.Dimension(300, 65));
        cnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnPanelMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Centre");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/center-logo.png"))); // NOI18N

        javax.swing.GroupLayout cnPanelLayout = new javax.swing.GroupLayout(cnPanel);
        cnPanel.setLayout(cnPanelLayout);
        cnPanelLayout.setHorizontalGroup(
                cnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cnPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        cnPanelLayout.setVerticalGroup(
                cnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cnPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(cnPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                .addContainerGap(23, Short.MAX_VALUE)));

        vaPanel.setBackground(new java.awt.Color(0, 109, 119));
        vaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaPanel.setPreferredSize(new java.awt.Dimension(300, 65));
        vaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaPanelMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaPanelMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaPanelMouseExited(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Vaccine");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine-panel.png"))); // NOI18N

        javax.swing.GroupLayout vaPanelLayout = new javax.swing.GroupLayout(vaPanel);
        vaPanel.setLayout(vaPanelLayout);
        vaPanelLayout.setHorizontalGroup(
                vaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vaPanelLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        vaPanelLayout.setVerticalGroup(
                vaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vaPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(vaPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel37))
                                .addContainerGap(23, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dbPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(74, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                        .addComponent(ppPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vaPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(dbPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ppPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cnPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(vaPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351,
                                        Short.MAX_VALUE)
                                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pplName.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        pplName.setForeground(new java.awt.Color(226, 149, 120));
        pplName.setText("Josh Evan");

        jPanel2.setBackground(new java.awt.Color(237, 246, 249));

        pplCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplCategory.setForeground(new java.awt.Color(255, 255, 255));
        pplCategory.setText("Non-Citizen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addComponent(pplCategory)
                                .addGap(16, 16, 16)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addComponent(pplCategory)
                                .addGap(16, 16, 16)));

        jPanel4.setBackground(new java.awt.Color(237, 246, 249));

        vacStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vacStatus.setForeground(new java.awt.Color(255, 255, 255));
        vacStatus.setText("Registered for Vaccination");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addComponent(vacStatus)
                                .addGap(20, 20, 20)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(vacStatus)
                                .addContainerGap(16, Short.MAX_VALUE)));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 109, 119));
        idLabel.setText("IC:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 109, 119));
        jLabel15.setText("Gender:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 109, 119));
        jLabel16.setText("DOB:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 109, 119));
        jLabel17.setText("Age:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 109, 119));
        jLabel18.setText("Address:");

        pplAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplAddress.setForeground(new java.awt.Color(0, 109, 119));
        pplAddress.setText("456A, Jalan Asia Pacific, Johor, Malaysia, 456000");

        pplAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplAge.setForeground(new java.awt.Color(0, 109, 119));
        pplAge.setText("31");

        pplGender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplGender.setForeground(new java.awt.Color(0, 109, 119));
        pplGender.setText("Male");

        pplDOB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplDOB.setForeground(new java.awt.Color(0, 109, 119));
        pplDOB.setText("19/11/1990");

        pplId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplId.setForeground(new java.awt.Color(0, 109, 119));
        pplId.setText("901119-13-9731");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 109, 119));
        jLabel24.setText("Appointments");

        firstDosePanel.setBackground(new java.awt.Color(237, 246, 249));

        firstDoseLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstDoseLbl.setForeground(new java.awt.Color(255, 255, 255));
        firstDoseLbl.setText("1st Dose");

        firstDoseLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstDoseLocation.setForeground(new java.awt.Color(0, 109, 119));
        firstDoseLocation.setText("Bukit Jalil");

        firstDoseDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstDoseDate.setForeground(new java.awt.Color(255, 255, 255));
        firstDoseDate.setText("11/09/2021 9:00am");

        firstDoseVacPanel.setBackground(new java.awt.Color(0, 109, 119));

        firstDoseVac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstDoseVac.setForeground(new java.awt.Color(255, 255, 255));
        firstDoseVac.setText("Phizer");

        javax.swing.GroupLayout firstDoseVacPanelLayout = new javax.swing.GroupLayout(firstDoseVacPanel);
        firstDoseVacPanel.setLayout(firstDoseVacPanelLayout);
        firstDoseVacPanelLayout.setHorizontalGroup(
                firstDoseVacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstDoseVacPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(firstDoseVac)
                                .addContainerGap(65, Short.MAX_VALUE)));
        firstDoseVacPanelLayout.setVerticalGroup(
                firstDoseVacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                firstDoseVacPanelLayout.createSequentialGroup()
                                        .addContainerGap(16, Short.MAX_VALUE)
                                        .addComponent(firstDoseVac)
                                        .addGap(16, 16, 16)));

        firstDoseDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstDoseDone.setForeground(new java.awt.Color(226, 149, 120));
        firstDoseDone.setText("Done");

        javax.swing.GroupLayout firstDosePanelLayout = new javax.swing.GroupLayout(firstDosePanel);
        firstDosePanel.setLayout(firstDosePanelLayout);
        firstDosePanelLayout.setHorizontalGroup(
                firstDosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstDosePanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(firstDosePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(firstDosePanelLayout.createSequentialGroup()
                                                .addComponent(firstDoseLbl)
                                                .addGap(260, 260, 260)
                                                .addComponent(firstDoseDone))
                                        .addComponent(firstDoseDate)
                                        .addComponent(firstDoseLocation)
                                        .addComponent(firstDoseVacPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(48, Short.MAX_VALUE)));
        firstDosePanelLayout.setVerticalGroup(
                firstDosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstDosePanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(firstDosePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstDoseLbl)
                                        .addComponent(firstDoseDone))
                                .addGap(16, 16, 16)
                                .addComponent(firstDoseLocation)
                                .addGap(16, 16, 16)
                                .addComponent(firstDoseDate)
                                .addGap(16, 16, 16)
                                .addComponent(firstDoseVacPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE)));

        backBtn.setBackground(new java.awt.Color(237, 246, 249));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setPreferredSize(new java.awt.Dimension(58, 22));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-btn.png"))); // NOI18N
        jLabel33.setText("Back");

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
                backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backBtnLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel33)
                                .addGap(20, 20, 20)));
        backBtnLayout.setVerticalGroup(
                backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backBtnLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel33)
                                .addGap(12, 12, 12)));

        editPeopleInfo.setBackground(new java.awt.Color(0, 109, 119));
        editPeopleInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPeopleInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPeopleInfoMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Edit Info");

        javax.swing.GroupLayout editPeopleInfoLayout = new javax.swing.GroupLayout(editPeopleInfo);
        editPeopleInfo.setLayout(editPeopleInfoLayout);
        editPeopleInfoLayout.setHorizontalGroup(
                editPeopleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPeopleInfoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel36)
                                .addGap(26, 26, 26)));
        editPeopleInfoLayout.setVerticalGroup(
                editPeopleInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPeopleInfoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel36)
                                .addGap(12, 12, 12)));

        secDosePanel.setBackground(new java.awt.Color(237, 246, 249));

        secDoseLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secDoseLbl.setForeground(new java.awt.Color(255, 255, 255));
        secDoseLbl.setText("2nd Dose");

        secDoseLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        secDoseLocation.setForeground(new java.awt.Color(0, 109, 119));
        secDoseLocation.setText("Bukit Jalil");

        secDoseDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secDoseDate.setForeground(new java.awt.Color(255, 255, 255));
        secDoseDate.setText("11/09/2021 9:00am");

        secDoseVacPanel.setBackground(new java.awt.Color(0, 109, 119));

        secDoseVac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secDoseVac.setForeground(new java.awt.Color(255, 255, 255));
        secDoseVac.setText("Phizer");

        javax.swing.GroupLayout secDoseVacPanelLayout = new javax.swing.GroupLayout(secDoseVacPanel);
        secDoseVacPanel.setLayout(secDoseVacPanelLayout);
        secDoseVacPanelLayout.setHorizontalGroup(
                secDoseVacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(secDoseVacPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(secDoseVac)
                                .addContainerGap(65, Short.MAX_VALUE)));
        secDoseVacPanelLayout.setVerticalGroup(
                secDoseVacPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                secDoseVacPanelLayout.createSequentialGroup()
                                        .addContainerGap(16, Short.MAX_VALUE)
                                        .addComponent(secDoseVac)
                                        .addGap(16, 16, 16)));

        secDoseDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secDoseDone.setForeground(new java.awt.Color(226, 149, 120));
        secDoseDone.setText("Done");

        javax.swing.GroupLayout secDosePanelLayout = new javax.swing.GroupLayout(secDosePanel);
        secDosePanel.setLayout(secDosePanelLayout);
        secDosePanelLayout.setHorizontalGroup(
                secDosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(secDosePanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(secDosePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(secDosePanelLayout.createSequentialGroup()
                                                .addComponent(secDoseVacPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(secDosePanelLayout.createSequentialGroup()
                                                .addComponent(secDoseDate)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(secDosePanelLayout.createSequentialGroup()
                                                .addGroup(secDosePanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(secDoseLocation)
                                                        .addComponent(secDoseLbl))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        227, Short.MAX_VALUE)
                                                .addComponent(secDoseDone)
                                                .addGap(50, 50, 50)))));
        secDosePanelLayout.setVerticalGroup(
                secDosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(secDosePanelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(secDosePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(secDoseLbl)
                                        .addComponent(secDoseDone))
                                .addGap(16, 16, 16)
                                .addComponent(secDoseLocation)
                                .addGap(16, 16, 16)
                                .addComponent(secDoseDate)
                                .addGap(16, 16, 16)
                                .addComponent(secDoseVacPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        scheduleAppointment.setBackground(new java.awt.Color(0, 109, 119));
        scheduleAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scheduleAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleAppointmentMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Schedule Appointment");

        javax.swing.GroupLayout scheduleAppointmentLayout = new javax.swing.GroupLayout(scheduleAppointment);
        scheduleAppointment.setLayout(scheduleAppointmentLayout);
        scheduleAppointmentLayout.setHorizontalGroup(
                scheduleAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scheduleAppointmentLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel39)
                                .addContainerGap(26, Short.MAX_VALUE)));
        scheduleAppointmentLayout.setVerticalGroup(
                scheduleAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(scheduleAppointmentLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel39)
                                .addContainerGap(12, Short.MAX_VALUE)));

        registerVaccination.setBackground(new java.awt.Color(0, 109, 119));
        registerVaccination.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerVaccination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerVaccinationMouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Register for Vaccination");

        javax.swing.GroupLayout registerVaccinationLayout = new javax.swing.GroupLayout(registerVaccination);
        registerVaccination.setLayout(registerVaccinationLayout);
        registerVaccinationLayout.setHorizontalGroup(
                registerVaccinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerVaccinationLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel40)
                                .addContainerGap(15, Short.MAX_VALUE)));
        registerVaccinationLayout.setVerticalGroup(
                registerVaccinationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerVaccinationLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel40)
                                .addContainerGap(12, Short.MAX_VALUE)));

        javax.swing.GroupLayout formBackgroundLayout = new javax.swing.GroupLayout(formBackground);
        formBackground.setLayout(formBackgroundLayout);
        formBackgroundLayout.setHorizontalGroup(
                formBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(formBackgroundLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addGroup(formBackgroundLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel18)
                                                                        .addComponent(jLabel17)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(idLabel))
                                                                .addGap(40, 40, 40)
                                                                .addGroup(formBackgroundLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pplId)
                                                                        .addComponent(pplGender)
                                                                        .addComponent(pplAge)
                                                                        .addComponent(pplAddress)
                                                                        .addComponent(pplDOB))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formBackgroundLayout
                                                .createSequentialGroup()
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jPanel4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(registerVaccination,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addComponent(firstDosePanel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        55, Short.MAX_VALUE)
                                                                .addComponent(secDosePanel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addComponent(pplName)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(editPeopleInfo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addComponent(jLabel24)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(scheduleAppointment,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(67, 67, 67)))));
        formBackgroundLayout.setVerticalGroup(
                formBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                .addGroup(formBackgroundLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(formBackgroundLayout.createSequentialGroup()
                                                                .addGroup(formBackgroundLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(pplName)
                                                                        .addComponent(editPeopleInfo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(formBackgroundLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(registerVaccination,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(idLabel)
                                                        .addComponent(pplId))
                                                .addGap(14, 14, 14)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(pplGender))
                                                .addGap(14, 14, 14)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(pplDOB))
                                                .addGap(14, 14, 14)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel17)
                                                        .addComponent(pplAge))
                                                .addGap(14, 14, 14)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel18)
                                                        .addComponent(pplAddress))
                                                .addGap(23, 23, 23)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel24)
                                                        .addComponent(scheduleAppointment,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(formBackgroundLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(secDosePanel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(firstDosePanel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formBackground, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbPanelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dbPanelMouseEntered
        dbPanel.setBackground(secColor);
    }// GEN-LAST:event_dbPanelMouseEntered

    private void dbPanelMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dbPanelMouseExited
        dbPanel.setBackground(priColor);
    }// GEN-LAST:event_dbPanelMouseExited

    private void vaPanelMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_vaPanelMouseEntered
        vaPanel.setBackground(secColor);
    }// GEN-LAST:event_vaPanelMouseEntered

    private void vaPanelMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_vaPanelMouseExited
        vaPanel.setBackground(priColor);
    }// GEN-LAST:event_vaPanelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_logoutPanelMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Exit program",
                JOptionPane.ERROR_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            Login log = new Login();

            setVisible(false);
            log.setVisible(true);
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }// GEN-LAST:event_logoutPanelMouseClicked

    private void vaPanelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_vaPanelMouseClicked
        PersonnelVaccine pv = new PersonnelVaccine();
        pv.setVisible(true);
    }// GEN-LAST:event_vaPanelMouseClicked

    private void dbPanelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_dbPanelMouseClicked
        PersonnelDashboard pd = new PersonnelDashboard();
        this.setVisible(false);
        pd.setVisible(true);
    }// GEN-LAST:event_dbPanelMouseClicked

    private void cnPanelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cnPanelMouseClicked
        PersonnelCentre pc = new PersonnelCentre();
        this.setVisible(false);
        pc.setVisible(true);
    }// GEN-LAST:event_cnPanelMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_backBtnMouseClicked
        PersonnelPeopleList ppl = new PersonnelPeopleList();
        ppl.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_backBtnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        String id = pplId.getText();
        scheduleAppointment.setVisible(false);
        firstDosePanel.setVisible(false);
        secDosePanel.setVisible(false);
        firstDoseDone.setVisible(false);
        secDoseDone.setVisible(false);
        firstDoseVacPanel.setVisible(false);

        try {
            // fetch data
            ppl.generatePeopleList();
            peopleList = ppl.getPeopleList();
            c.generateCentreList();
            centreList = c.getCentreList();

            // Set the value or the labels (people detail)
            ppl.searchUser(peopleList, id);
            pplName.setText(ppl.getName());
            pplCategory.setText(ppl.getCategory());
            pplGender.setText(ppl.getGender());
            pplDOB.setText(ppl.getDOB());
            pplAge.setText(Integer.toString(ppl.getAge()));
            if ("Citizen".equals(ppl.getCategory())) {
                pplAddress.setText(ppl.getAddress());
            } else {
                pplAddress.setText(ppl.getCountry());
            }
            vacStatus.setText(ppl.getVaccinationStatus());

            if ("Not Registered".equals(ppl.getVaccinationStatus())) {
                registerVaccination.setVisible(true);
            } else {
                registerVaccination.setVisible(false);
            }

            ap.generateAppointmentList();
            appointmentList = ap.getAppointmentList();

            // Display the appointment schedule
            Appointment ap1 = new Appointment();
            Appointment ap2 = new Appointment();

            // ap.searchAppointment(appointmentList, 0, id);
            boolean firstDoseExist;
            try {
                firstDoseExist = ap1.checkDose(1, id);
                if (firstDoseExist) {
                    firstDosePanel.setVisible(true);
                    firstDoseLocation.setText(ap1.getVenue());
                    // time haven't set
                    if (ap1.getAppointmentDate() == null) {
                        firstDoseDate.setText("-");
                        scheduleAppointment.setVisible(true);
                    } else {
                        firstDoseDate.setText(ap1.getAppointmentDate() + " " + ap1.getAppointmentTime());
                    }

                    String vacName = ap1.getVaccine();
                    if (!"-".equals(vacName)) {
                        firstDoseVacPanel.setVisible(true);
                        firstDoseVac.setText(vacName);
                    } else {
                        firstDoseVacPanel.setVisible(false);
                    }

                    String completed = ap1.getCompleted();
                    if (completed.equals("Yes")) {
                        firstDoseDone.setVisible(true);
                    }
                } else {
                    // scheduleAppointment.setVisible(true);
                }
            } catch (ParseException ex) {
                Logger.getLogger(PersonnelPeople.class.getName()).log(Level.SEVERE, null, ex);
            }

            boolean secDoseExist;
            try {
                secDoseExist = ap2.checkDose(2, id);
                if (secDoseExist) {
                    secDosePanel.setVisible(true);
                    secDoseLocation.setText(ap2.getVenue());
                    // time haven't set
                    if (ap2.getAppointmentDate() == null) {
                        secDoseDate.setText("-");
                    } else {
                        secDoseDate.setText(ap2.getAppointmentDate() + " " + ap2.getAppointmentTime());
                    }

                    String vacName = ap2.getVaccine();
                    if (!"-".equals(vacName)) {
                        secDoseVacPanel.setVisible(true);
                        secDoseVac.setText(vacName);
                    } else {
                        secDoseVacPanel.setVisible(false);
                    }

                    String completed = ap2.getCompleted();
                    if (completed.equals("Yes")) {
                        secDoseDone.setVisible(true);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(PersonnelPeople.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPeople.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_formWindowOpened

    private void editPeopleInfoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_editPeopleInfoMouseClicked
        String id = pplId.getText();
        PersonnelEditPeople pep = new PersonnelEditPeople(id);
        pep.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_editPeopleInfoMouseClicked

    private void scheduleAppointmentMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_scheduleAppointmentMouseClicked
        String vaccinationStatus = vacStatus.getText();
        if (vaccinationStatus.equals("Not Registered")) {
            JOptionPane.showMessageDialog(this, "Please register for vaccination first!", "Error Message",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            PersonnelAddAppointment paa = new PersonnelAddAppointment(firstDoseLocation.getText(), pplId.getText());
            paa.setVisible(true);
            this.setVisible(false);

            // try {
            // // combo box elements
            // Object[] centreName = c.getAllCentreName();
            // // combo box to choose centre
            // JComboBox cb = new JComboBox(centreName);
            //
            // // joption pane
            // int input;
            // input = JOptionPane.showConfirmDialog(this, cb, "Add new appointment for...",
            // JOptionPane.DEFAULT_OPTION);
            //
            // // get selected item
            // if (input == JOptionPane.OK_OPTION) {
            // String selected = (String) cb.getSelectedItem();
            // PersonnelAddAppointment paa = new PersonnelAddAppointment(selected,
            // pplId.getText());
            // paa.setVisible(true);
            // this.setVisible(false);
            // }
            // } catch (FileNotFoundException ex) {
            // Logger.getLogger(PersonnelDashboard.class.getName()).log(Level.SEVERE, null,
            // ex);
            // }
        }
    }// GEN-LAST:event_scheduleAppointmentMouseClicked

    private void registerVaccinationMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_registerVaccinationMouseClicked
        RegisterVaccine rv = new RegisterVaccine();
        rv.peopleInfo(pplId.getText(), 1);
        rv.setVisible(true);
        this.setVisible(false);
        
    }// GEN-LAST:event_registerVaccinationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelPeople.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelPeople.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelPeople.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelPeople.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelPeople().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel cnPanel;
    private javax.swing.JPanel dbPanel;
    private javax.swing.JPanel editPeopleInfo;
    private javax.swing.JLabel firstDoseDate;
    private javax.swing.JLabel firstDoseDone;
    private javax.swing.JLabel firstDoseLbl;
    private javax.swing.JLabel firstDoseLocation;
    private javax.swing.JPanel firstDosePanel;
    private javax.swing.JLabel firstDoseVac;
    private javax.swing.JPanel firstDoseVacPanel;
    private javax.swing.JPanel formBackground;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel ppPanel;
    private javax.swing.JLabel pplAddress;
    private javax.swing.JLabel pplAge;
    private javax.swing.JLabel pplCategory;
    private javax.swing.JLabel pplDOB;
    private javax.swing.JLabel pplGender;
    private javax.swing.JLabel pplId;
    private javax.swing.JLabel pplName;
    private javax.swing.JPanel registerVaccination;
    private javax.swing.JPanel scheduleAppointment;
    private javax.swing.JLabel secDoseDate;
    private javax.swing.JLabel secDoseDone;
    private javax.swing.JLabel secDoseLbl;
    private javax.swing.JLabel secDoseLocation;
    private javax.swing.JPanel secDosePanel;
    private javax.swing.JLabel secDoseVac;
    private javax.swing.JPanel secDoseVacPanel;
    private javax.swing.JPanel vaPanel;
    private javax.swing.JLabel vacStatus;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(Color bgColor) {
            super();
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            // Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); // paint background
            graphics.setColor(getForeground());
            // graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);
            // //paint border
            //
        }
    }

}
