import classes.Citizen;
import classes.People;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dexte
 */
public class RegisterAccount extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAccount
     */
    Color priColor = new Color(0,109,119);
    Color secColor = new Color(131, 197, 190);
    Color bgColor = new Color(237,246,249);
    Color empColor = new Color(255,221,210);
    Color whiteColor = new Color(255,255,255);
    
    People ppl = new People();
    Citizen citi = new Citizen();
 
    public RegisterAccount() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/vaccine-logo.png")));
        String signin = "<html><u>Sign In</u></html>";
        goLoginForm.setText(signin);
        String tnc = "<html><u>Terms & Conditions</u></html>";
        viewTnc.setText(tnc);
        hidepassword1.setVisible(false);
        hidepassword2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        logoPanel = new RoundedPanel(20, priColor);
        logolabel3 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        youarelabel = new javax.swing.JLabel();
        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        conpasslabel = new javax.swing.JLabel();
        viewTnc = new javax.swing.JLabel();
        pplName = new javax.swing.JTextField();
        TncCheckButton = new javax.swing.JCheckBox();
        pplMalaysian = new javax.swing.JRadioButton();
        pplForeigner = new javax.swing.JRadioButton();
        pplFname = new javax.swing.JTextField();
        fnamelabel = new javax.swing.JLabel();
        pplIcpass = new javax.swing.JTextField();
        icpasslabel = new javax.swing.JLabel();
        pplAddress = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        regisButtonPanel = new RoundedPanel(5, priColor);
        registerButton = new javax.swing.JLabel();
        pplPostcode = new javax.swing.JTextField();
        postclabel = new javax.swing.JLabel();
        pplCountry = new javax.swing.JTextField();
        countlabel = new javax.swing.JLabel();
        pplState = new javax.swing.JTextField();
        statelabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        pplFemale = new javax.swing.JRadioButton();
        pplMale = new javax.swing.JRadioButton();
        doblabel = new javax.swing.JLabel();
        pplDOB = new com.toedter.calendar.JDateChooser();
        pplConPass = new javax.swing.JPasswordField();
        pplPassword = new javax.swing.JPasswordField();
        showpassword2 = new javax.swing.JLabel();
        showpassword1 = new javax.swing.JLabel();
        hidepassword1 = new javax.swing.JLabel();
        hidepassword2 = new javax.swing.JLabel();
        createacclabel = new javax.swing.JLabel();
        fstoplabel = new javax.swing.JLabel();
        havaacclabel = new javax.swing.JLabel();
        goLoginForm = new javax.swing.JLabel();
        seperateline = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        basePanel.setBackground(new java.awt.Color(237, 246, 249));
        basePanel.setMinimumSize(new java.awt.Dimension(1440, 800));
        basePanel.setPreferredSize(new java.awt.Dimension(1440, 800));

        logoPanel.setBackground(new java.awt.Color(237, 246, 249));
        logoPanel.setPreferredSize(new java.awt.Dimension(228, 86));

        logolabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccineo-logo-big.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(logolabel3)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(logolabel3)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        formPanel.setBackground(new java.awt.Color(237, 246, 249));
        formPanel.setPreferredSize(new java.awt.Dimension(380, 562));
        formPanel.setLayout(null);

        youarelabel.setBackground(new java.awt.Color(0, 109, 119));
        youarelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        youarelabel.setForeground(new java.awt.Color(0, 109, 119));
        youarelabel.setText("You are? ");
        formPanel.add(youarelabel);
        youarelabel.setBounds(399, 4, 85, 22);

        userlabel.setBackground(new java.awt.Color(0, 109, 119));
        userlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userlabel.setForeground(new java.awt.Color(0, 109, 119));
        userlabel.setText("Username");
        formPanel.add(userlabel);
        userlabel.setBounds(0, 4, 78, 22);

        passlabel.setBackground(new java.awt.Color(0, 109, 119));
        passlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passlabel.setForeground(new java.awt.Color(0, 109, 119));
        passlabel.setText("Password");
        formPanel.add(passlabel);
        passlabel.setBounds(0, 113, 74, 22);

        conpasslabel.setBackground(new java.awt.Color(0, 109, 119));
        conpasslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        conpasslabel.setForeground(new java.awt.Color(0, 109, 119));
        conpasslabel.setText("Confirm Password");
        formPanel.add(conpasslabel);
        conpasslabel.setBounds(0, 218, 142, 22);

        viewTnc.setBackground(new java.awt.Color(0, 109, 119));
        viewTnc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewTnc.setForeground(new java.awt.Color(226, 149, 120));
        viewTnc.setText("Terms & Conditions");
        viewTnc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTncMouseClicked(evt);
            }
        });
        formPanel.add(viewTnc);
        viewTnc.setBounds(21, 358, 119, 17);

        pplName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplName.setToolTipText("");
        pplName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplName.setCaretColor(new java.awt.Color(0, 109, 119));
        pplName.setPreferredSize(new java.awt.Dimension(318, 54));
        formPanel.add(pplName);
        pplName.setBounds(0, 41, 338, 54);

        TncCheckButton.setBackground(new java.awt.Color(237, 246, 249));
        TncCheckButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TncCheckButton.setForeground(new java.awt.Color(0, 109, 119));
        TncCheckButton.setText("By creating an account, you are agree to our");
        formPanel.add(TncCheckButton);
        TncCheckButton.setBounds(0, 331, 303, 25);

        pplMalaysian.setBackground(new java.awt.Color(237, 246, 249));
        pplMalaysian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplMalaysian.setForeground(new java.awt.Color(0, 109, 119));
        pplMalaysian.setSelected(true);
        pplMalaysian.setText("Malaysian");
        pplMalaysian.setContentAreaFilled(false);
        pplMalaysian.setFocusPainted(false);
        pplMalaysian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pplMalaysianActionPerformed(evt);
            }
        });
        formPanel.add(pplMalaysian);
        pplMalaysian.setBounds(512, 0, 101, 30);

        pplForeigner.setBackground(new java.awt.Color(237, 246, 249));
        pplForeigner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplForeigner.setForeground(new java.awt.Color(0, 109, 119));
        pplForeigner.setText("Foreigner");
        pplForeigner.setContentAreaFilled(false);
        pplForeigner.setFocusPainted(false);
        pplForeigner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pplForeignerActionPerformed(evt);
            }
        });
        formPanel.add(pplForeigner);
        pplForeigner.setBounds(631, 0, 98, 30);

        pplFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplFname.setToolTipText("");
        pplFname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplFname.setCaretColor(new java.awt.Color(0, 109, 119));
        pplFname.setPreferredSize(new java.awt.Dimension(352, 54));
        formPanel.add(pplFname);
        pplFname.setBounds(399, 84, 352, 54);

        fnamelabel.setBackground(new java.awt.Color(0, 109, 119));
        fnamelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnamelabel.setForeground(new java.awt.Color(0, 109, 119));
        fnamelabel.setText("Full Name");
        formPanel.add(fnamelabel);
        fnamelabel.setBounds(399, 48, 78, 22);

        pplIcpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplIcpass.setToolTipText("");
        pplIcpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplIcpass.setCaretColor(new java.awt.Color(0, 109, 119));
        pplIcpass.setPreferredSize(new java.awt.Dimension(318, 54));
        pplIcpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pplIcpassKeyTyped(evt);
            }
        });
        formPanel.add(pplIcpass);
        pplIcpass.setBounds(399, 196, 318, 54);

        icpasslabel.setBackground(new java.awt.Color(0, 109, 119));
        icpasslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        icpasslabel.setForeground(new java.awt.Color(0, 109, 119));
        icpasslabel.setText("IC / Passport");
        formPanel.add(icpasslabel);
        icpasslabel.setBounds(399, 163, 104, 22);

        pplAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplAddress.setToolTipText("");
        pplAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplAddress.setCaretColor(new java.awt.Color(0, 109, 119));
        pplAddress.setPreferredSize(new java.awt.Dimension(374, 54));
        formPanel.add(pplAddress);
        pplAddress.setBounds(399, 301, 374, 54);

        addresslabel.setBackground(new java.awt.Color(0, 109, 119));
        addresslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(0, 109, 119));
        addresslabel.setText("Address");
        formPanel.add(addresslabel);
        addresslabel.setBounds(399, 268, 62, 22);

        regisButtonPanel.setBackground(new java.awt.Color(237, 246, 249));
        regisButtonPanel.setPreferredSize(new java.awt.Dimension(318, 54));

        registerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerButton.setText("Sign Up");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.setPreferredSize(new java.awt.Dimension(62, 54));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout regisButtonPanelLayout = new javax.swing.GroupLayout(regisButtonPanel);
        regisButtonPanel.setLayout(regisButtonPanelLayout);
        regisButtonPanelLayout.setHorizontalGroup(
            regisButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisButtonPanelLayout.createSequentialGroup()
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        regisButtonPanelLayout.setVerticalGroup(
            regisButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regisButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        formPanel.add(regisButtonPanel);
        regisButtonPanel.setBounds(0, 406, 338, 54);

        pplPostcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplPostcode.setToolTipText("");
        pplPostcode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplPostcode.setCaretColor(new java.awt.Color(0, 109, 119));
        pplPostcode.setPreferredSize(new java.awt.Dimension(280, 54));
        pplPostcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pplPostcodeKeyTyped(evt);
            }
        });
        formPanel.add(pplPostcode);
        pplPostcode.setBounds(399, 406, 280, 54);

        postclabel.setBackground(new java.awt.Color(0, 109, 119));
        postclabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postclabel.setForeground(new java.awt.Color(0, 109, 119));
        postclabel.setText("Postcode");
        formPanel.add(postclabel);
        postclabel.setBounds(399, 373, 71, 22);

        pplCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplCountry.setToolTipText("");
        pplCountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplCountry.setCaretColor(new java.awt.Color(0, 109, 119));
        pplCountry.setPreferredSize(new java.awt.Dimension(280, 54));
        formPanel.add(pplCountry);
        pplCountry.setBounds(705, 406, 280, 54);

        countlabel.setBackground(new java.awt.Color(0, 109, 119));
        countlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countlabel.setForeground(new java.awt.Color(0, 109, 119));
        countlabel.setText("Country");
        formPanel.add(countlabel);
        countlabel.setBounds(705, 373, 62, 22);

        pplState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplState.setToolTipText("");
        pplState.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplState.setCaretColor(new java.awt.Color(0, 109, 119));
        pplState.setPreferredSize(new java.awt.Dimension(374, 54));
        formPanel.add(pplState);
        pplState.setBounds(799, 301, 186, 54);

        statelabel.setBackground(new java.awt.Color(0, 109, 119));
        statelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statelabel.setForeground(new java.awt.Color(0, 109, 119));
        statelabel.setText("State");
        formPanel.add(statelabel);
        statelabel.setBounds(799, 268, 40, 22);

        genderlabel.setBackground(new java.awt.Color(0, 109, 119));
        genderlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderlabel.setForeground(new java.awt.Color(0, 109, 119));
        genderlabel.setText("Gender");
        formPanel.add(genderlabel);
        genderlabel.setBounds(800, 48, 56, 22);

        pplFemale.setBackground(new java.awt.Color(237, 246, 249));
        pplFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplFemale.setForeground(new java.awt.Color(0, 109, 119));
        pplFemale.setText("Female");
        pplFemale.setContentAreaFilled(false);
        pplFemale.setFocusPainted(false);
        pplFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pplFemaleActionPerformed(evt);
            }
        });
        formPanel.add(pplFemale);
        pplFemale.setBounds(879, 96, 80, 30);

        pplMale.setBackground(new java.awt.Color(237, 246, 249));
        pplMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplMale.setForeground(new java.awt.Color(0, 109, 119));
        pplMale.setText("Male");
        pplMale.setContentAreaFilled(false);
        pplMale.setFocusPainted(false);
        pplMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pplMaleActionPerformed(evt);
            }
        });
        formPanel.add(pplMale);
        pplMale.setBounds(795, 96, 61, 30);

        doblabel.setBackground(new java.awt.Color(0, 109, 119));
        doblabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doblabel.setForeground(new java.awt.Color(0, 109, 119));
        doblabel.setText("Date of Birth");
        formPanel.add(doblabel);
        doblabel.setBounds(743, 163, 101, 22);

        pplDOB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 109, 119), 2, true));
        pplDOB.setDateFormatString("dd/MM/yyyy");
        formPanel.add(pplDOB);
        pplDOB.setBounds(743, 196, 242, 54);

        pplConPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplConPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 109, 119), 2));
        pplConPass.setEchoChar('*');
        pplConPass.setPreferredSize(new java.awt.Dimension(318, 54));
        formPanel.add(pplConPass);
        pplConPass.setBounds(0, 250, 300, 54);

        pplPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pplPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 109, 119), 2));
        pplPassword.setEchoChar('*');
        pplPassword.setPreferredSize(new java.awt.Dimension(318, 54));
        formPanel.add(pplPassword);
        pplPassword.setBounds(0, 150, 300, 54);

        showpassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-showpass.png"))); // NOI18N
        showpassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassword2MouseClicked(evt);
            }
        });
        formPanel.add(showpassword2);
        showpassword2.setBounds(310, 250, 24, 50);

        showpassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-showpass.png"))); // NOI18N
        showpassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassword1MouseClicked(evt);
            }
        });
        formPanel.add(showpassword1);
        showpassword1.setBounds(310, 150, 24, 50);

        hidepassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-hidepass.png"))); // NOI18N
        hidepassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidepassword1MouseClicked(evt);
            }
        });
        formPanel.add(hidepassword1);
        hidepassword1.setBounds(310, 150, 23, 50);

        hidepassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regis-hidepass.png"))); // NOI18N
        hidepassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidepassword2MouseClicked(evt);
            }
        });
        formPanel.add(hidepassword2);
        hidepassword2.setBounds(310, 250, 23, 50);

        createacclabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        createacclabel.setForeground(new java.awt.Color(0, 109, 119));
        createacclabel.setText("Create a new account");

        fstoplabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fstoplabel.setForeground(new java.awt.Color(131, 197, 190));
        fstoplabel.setText(".");

        havaacclabel.setBackground(new java.awt.Color(0, 109, 119));
        havaacclabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        havaacclabel.setForeground(new java.awt.Color(0, 109, 119));
        havaacclabel.setText("Already have an account?");

        goLoginForm.setBackground(new java.awt.Color(0, 109, 119));
        goLoginForm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goLoginForm.setForeground(new java.awt.Color(226, 149, 120));
        goLoginForm.setText("Sign In");
        goLoginForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goLoginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goLoginFormMouseClicked(evt);
            }
        });

        seperateline.setBackground(new java.awt.Color(0, 109, 119));
        seperateline.setPreferredSize(new java.awt.Dimension(300, 1));

        javax.swing.GroupLayout seperatelineLayout = new javax.swing.GroupLayout(seperateline);
        seperateline.setLayout(seperatelineLayout);
        seperatelineLayout.setHorizontalGroup(
            seperatelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        seperatelineLayout.setVerticalGroup(
            seperatelineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(createacclabel)
                        .addGap(7, 7, 7)
                        .addComponent(fstoplabel)
                        .addGap(309, 309, 309)
                        .addComponent(havaacclabel)
                        .addGap(8, 8, 8)
                        .addComponent(goLoginForm))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(seperateline, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createacclabel)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fstoplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(havaacclabel)
                            .addComponent(goLoginForm))))
                .addGap(8, 8, 8)
                .addComponent(seperateline, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        String username = pplName.getText();
        String name = pplFname.getText();
        String id = pplIcpass.getText();
        String address = pplAddress.getText();
        String state = pplState.getText();
        String country = pplCountry.getText();
        String postcode = pplPostcode.getText();
        String pass = pplPassword.getText();
        String conpass = pplConPass.getText();
        String dob = ((JTextField)pplDOB.getDateEditor().getUiComponent()).getText();
        
        if(dob.length() == 0){
            JOptionPane.showMessageDialog(null, "Please fill in your Date of Birth.");
        } else {
            //User choose their category either Malaysian (citizen) or Foreigber (non-citizen)
            String category = null;
            if(pplMalaysian.isSelected()){
                category = "Citizen";
                if(postcode.length() == 0){
                    JOptionPane.showMessageDialog(null, "Please fill in your Postcode.");
                }
                if(address.length() == 0){
                    JOptionPane.showMessageDialog(null, "Please fill in your Address.");
                }
                if(state.length() == 0){
                    JOptionPane.showMessageDialog(null, "Please fill in your State.");
                } else {
                    //User choose their gender
                    String gender = null;
                    if(pplMale.isSelected()){
                        gender = "Male";
                        String password = null;
                        if(conpass.equals(pass)){
                            password = conpass;
                            //if checkbox not selected
                            if(TncCheckButton.isSelected()){
                                if(ppl.validatePass(pass) == false){
                                    JOptionPane.showMessageDialog(null, "The password must at least 8 characters and consist of 1 UpperCase, 1 LowerCase and 1 Number");
                                } else {
                                    if(citi.checkFormat(id) == true){
                                        try {
                                            ppl.registerPeople(username,name,id,address,state,country,postcode,password,gender,category,dob);
                                            this.setVisible(false);
                                            Login login = new Login();
                                            login.setVisible(true);
                                        }
                                        catch(Exception e){
                                            System.out.println("Error");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Please key in the correct IC numbers");
                                        } 
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Please agree to the Terms & Conditions.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please key in the same Password.");
                        }
                    } else if(pplFemale.isSelected()){
                        gender = "Female";
                        String password = null;
                        if(conpass.equals(pass)){
                            password = conpass;
                            //if checkbox not selected
                            if(TncCheckButton.isSelected()){
                                if(ppl.validatePass(pass) == false){
                                    JOptionPane.showMessageDialog(null, "The password must at least 8 characters and consist of 1 UpperCase, 1 LowerCase and 1 Number");
                                } else {
                                    if(citi.checkFormat(id) == true){
                                        try {
                                            ppl.registerPeople(username,name,id,address,state,country,postcode,password,gender,category,dob);
                                            this.setVisible(false);
                                            Login login = new Login();
                                            login.setVisible(true);
                                        }
                                        catch(Exception e){
                                            System.out.println("Error");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Please key in the correct IC numbers");
                                        } 
                                }   
                            } else {
                                JOptionPane.showMessageDialog(null, "Please agree to the Terms & Conditions.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please key in the same Password.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please choose your Gender.");
                    }
                }
            }
            else if(pplForeigner.isSelected()){
                category = "Non-citizen";
                //User choose their gender
                String gender = null;
                if(pplMale.isSelected()){
                    gender = "Male";
                    String password = null;
                    if(conpass.equals(pass)){
                        password = conpass;
                        //if checkbox not selected
                        if(TncCheckButton.isSelected()){
                            if(ppl.validatePass(pass) == false){
                                JOptionPane.showMessageDialog(null, "The password must at least 8 characters and consist of 1 UpperCase, 1 LowerCase and 1 Number");
                            } else {
                                try {
                                    ppl.registerPeopleNon(username,name,id,address,password,gender,category,dob);
                                    this.setVisible(false);
                                    Login login = new Login();
                                    login.setVisible(true);
                                }
                                catch(Exception e){
                                    System.out.println("Error");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Please agree to the Terms & Conditions.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please key in the same Password.");
                    }
                } else if(pplFemale.isSelected()){
                    gender = "Female";
                    String password = null;
                    if(conpass.equals(pass)){
                        password = conpass;
                        //if checkbox not selected
                        if(TncCheckButton.isSelected()){
                            if(ppl.validatePass(pass) == false){
                                JOptionPane.showMessageDialog(null, "The password must at least 8 characters and consist of 1 UpperCase, 1 LowerCase and 1 Number");
                            } else {
                                try {
                                    ppl.registerPeopleNon(username,name,id,address,password,gender,category,dob);
                                    this.setVisible(false);
                                    Login login = new Login();
                                    login.setVisible(true);
                                }
                                catch(Exception e){
                                    System.out.println("Error");
                                }
                            }  
                        } else {
                            JOptionPane.showMessageDialog(null, "Please agree to the Terms & Conditions.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please key in the same Password.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please choose your Gender.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please choose you are Malaysian or Foreigner.");
            }
        }     
    }//GEN-LAST:event_registerButtonMouseClicked
 
    private void goLoginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goLoginFormMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_goLoginFormMouseClicked

    private void viewTncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTncMouseClicked
        // TODO add your handling code here:
        TermConditions tnc = new TermConditions();
        this.setVisible(false);
        tnc.setVisible(true);
    }//GEN-LAST:event_viewTncMouseClicked

    private void pplMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pplMaleActionPerformed
        // TODO add your handling code here:
        if(pplMale.isSelected()){
            pplFemale.setSelected(false);
        }
    }//GEN-LAST:event_pplMaleActionPerformed

    private void pplFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pplFemaleActionPerformed
        // TODO add your handling code here:
        if(pplFemale.isSelected()){
            pplMale.setSelected(false);
        }
    }//GEN-LAST:event_pplFemaleActionPerformed

    private void pplMalaysianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pplMalaysianActionPerformed
        // TODO add your handling code here:
        if(pplMalaysian.isSelected()){
            pplForeigner.setSelected(false);
            pplState.setVisible(true);
            pplCountry.setVisible(true);
            pplPostcode.setVisible(true);
            pplAddress.setSize(374, 54);
            addresslabel.setText("Address");
            statelabel.setVisible(true);
            countlabel.setVisible(true);
            postclabel.setVisible(true);
        }
    }//GEN-LAST:event_pplMalaysianActionPerformed

    private void pplForeignerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pplForeignerActionPerformed
        // TODO add your handling code here:
        //if Foreigner radio button is selected, foreigner only required to fill in country field.
        //Address, state and postcode field will be hidden.
        if(pplForeigner.isSelected()){
            pplMalaysian.setSelected(false);
            pplState.setVisible(false);
            pplCountry.setVisible(false);
            pplPostcode.setVisible(false);
            pplAddress.setSize(318, 54);
            addresslabel.setText("Country");
            statelabel.setVisible(false);
            countlabel.setVisible(false);
            postclabel.setVisible(false);
            revalidate();
        } else if(!pplForeigner.isSelected()) {
            pplState.setVisible(true);
            pplCountry.setVisible(true);
            pplPostcode.setVisible(true);
            pplAddress.setSize(374, 54);
            addresslabel.setText("Address");
            statelabel.setVisible(true);
            countlabel.setVisible(true);
            postclabel.setVisible(true);
        }
    }//GEN-LAST:event_pplForeignerActionPerformed

    private void pplPostcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pplPostcodeKeyTyped
        // TODO add your handling code here:
        //Only accept numbers and able to use the keyboard key "BACKSPACE" to remove numbers
        int nums =evt.getKeyChar();
        if(!(Character.isDigit(nums) || (nums==KeyEvent.VK_BACK_SPACE) || (nums==KeyEvent.VK_DELETE))){
            evt.consume();
        }
        //Maximum 5 numbers can be entered in the textfield
        if (pplPostcode.getText().length() >= 5 ) {// limit to 5 characters
                evt.consume();
        }
    }//GEN-LAST:event_pplPostcodeKeyTyped

    private void pplIcpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pplIcpassKeyTyped
        // TODO add your handling code here: 
            if(pplMalaysian.isSelected()){
                int icnums =evt.getKeyChar();
                if(!(Character.isDigit(icnums) || (icnums==KeyEvent.VK_BACK_SPACE) || (icnums==KeyEvent.VK_DELETE))){
                evt.consume();
            }
        }
    }//GEN-LAST:event_pplIcpassKeyTyped

    private void showpassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassword1MouseClicked
        // TODO add your handling code here:
            pplPassword.setEchoChar((char)0);
            pplConPass.setEchoChar((char)0);
            hidepassword1.setVisible(true);
            hidepassword2.setVisible(true);
            showpassword1.setVisible(false);
            showpassword2.setVisible(false);
    }//GEN-LAST:event_showpassword1MouseClicked

    private void hidepassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepassword1MouseClicked
        // TODO add your handling code here:
            pplPassword.setEchoChar('*');
            pplConPass.setEchoChar('*');
            hidepassword1.setVisible(false);
            hidepassword2.setVisible(false);
            showpassword1.setVisible(true);
            showpassword2.setVisible(true);
    }//GEN-LAST:event_hidepassword1MouseClicked

    private void showpassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassword2MouseClicked
        // TODO add your handling code here:
            pplPassword.setEchoChar((char)0);
            pplConPass.setEchoChar((char)0);
            hidepassword1.setVisible(true);
            hidepassword2.setVisible(true);
            showpassword1.setVisible(false);
            showpassword2.setVisible(false);
    }//GEN-LAST:event_showpassword2MouseClicked

    private void hidepassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepassword2MouseClicked
        // TODO add your handling code here:
            pplPassword.setEchoChar('*');
            pplConPass.setEchoChar('*');
            hidepassword1.setVisible(false);
            hidepassword2.setVisible(false);
            showpassword1.setVisible(true);
            showpassword2.setVisible(true);
    }//GEN-LAST:event_hidepassword2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox TncCheckButton;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JPanel basePanel;
    private javax.swing.JLabel conpasslabel;
    private javax.swing.JLabel countlabel;
    private javax.swing.JLabel createacclabel;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel fstoplabel;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JLabel goLoginForm;
    private javax.swing.JLabel havaacclabel;
    private javax.swing.JLabel hidepassword1;
    private javax.swing.JLabel hidepassword2;
    private javax.swing.JLabel icpasslabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logolabel3;
    private javax.swing.JLabel passlabel;
    private javax.swing.JLabel postclabel;
    private javax.swing.JTextField pplAddress;
    private javax.swing.JPasswordField pplConPass;
    private javax.swing.JTextField pplCountry;
    private com.toedter.calendar.JDateChooser pplDOB;
    private javax.swing.JRadioButton pplFemale;
    private javax.swing.JTextField pplFname;
    private javax.swing.JRadioButton pplForeigner;
    private javax.swing.JTextField pplIcpass;
    private javax.swing.JRadioButton pplMalaysian;
    private javax.swing.JRadioButton pplMale;
    private javax.swing.JTextField pplName;
    private javax.swing.JPasswordField pplPassword;
    private javax.swing.JTextField pplPostcode;
    private javax.swing.JTextField pplState;
    private javax.swing.JPanel regisButtonPanel;
    private javax.swing.JLabel registerButton;
    private javax.swing.JPanel seperateline;
    private javax.swing.JLabel showpassword1;
    private javax.swing.JLabel showpassword2;
    private javax.swing.JLabel statelabel;
    private javax.swing.JLabel userlabel;
    private javax.swing.JLabel viewTnc;
    private javax.swing.JLabel youarelabel;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel{
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;      
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border 
        }
    }
}
