
import classes.Appointment;
import classes.Centre;
import classes.GeneralFunction;
import classes.People;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dexte
 */
public class RegisterVaccine extends javax.swing.JFrame {

    /**
     * Creates new form RegisterVaccine
     */
    Color priColor = new Color(0, 109, 119);
    Color secColor = new Color(131, 197, 190);
    Color bgColor = new Color(237, 246, 249);
    Color empColor = new Color(255, 221, 210);
    Color whiteColor = new Color(255, 255, 255);

    String role;
    People ppl = new People();
    GeneralFunction gf = new GeneralFunction();
    Appointment app = new Appointment();
    Centre c = new Centre();
    ArrayList<ArrayList<String>> peopleList;

    public RegisterVaccine() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/vaccine-logo.png")));
    }

    public void peopleInfo(String value) {
        String id = value;
        try {
            ppl.generatePeopleList();
            peopleList = ppl.getPeopleList();
            ppl.searchUser(peopleList, id);
            ppl.setId(value);
            nameLabelView.setText(ppl.getName());
            idLabelView.setText(ppl.getId());
        } catch (Exception e) {
            Logger.getLogger(PersonnelPeople.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void peopleInfo(String value, String role) {
        String id = value;
        this.role = role;
        try {
            ppl.generatePeopleList();
            peopleList = ppl.getPeopleList();
            ppl.searchUser(peopleList, id);
            ppl.setId(value);
            nameLabelView.setText(ppl.getName());
            idLabelView.setText(ppl.getId());
        } catch (Exception e) {
            Logger.getLogger(PersonnelPeople.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        basepanel1 = new javax.swing.JPanel();
        navpanel4 = new javax.swing.JPanel();
        logolabel4 = new javax.swing.JLabel();
        ppllabel4 = new javax.swing.JLabel();
        logoutlabel4 = new javax.swing.JLabel();
        logopanel = new RoundedPanel(20, priColor);
        backbutton = new javax.swing.JButton();
        jPanel2 = new RoundedPanel(20, empColor);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(20, whiteColor);
        jLabel4 = new javax.swing.JLabel();
        nameLabelView = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idLabelView = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chooseCentre = new javax.swing.JComboBox<>();
        jPanel4 = new RoundedPanel(20, whiteColor);
        jLabel11 = new javax.swing.JLabel();
        yes1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        yes2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        yes3 = new javax.swing.JRadioButton();
        no3 = new javax.swing.JRadioButton();
        no4 = new javax.swing.JRadioButton();
        yes4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        no5 = new javax.swing.JRadioButton();
        yes5 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        no6 = new javax.swing.JRadioButton();
        yes6 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        yes7 = new javax.swing.JRadioButton();
        no7 = new javax.swing.JRadioButton();
        no8 = new javax.swing.JRadioButton();
        yes8 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new RoundedPanel(5, priColor);
        submitButton = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Vaccine");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1440, 800));

        basepanel1.setBackground(new java.awt.Color(237, 246, 249));
        basepanel1.setPreferredSize(new java.awt.Dimension(1440, 2200));

        navpanel4.setBackground(new java.awt.Color(0, 109, 119));

        logolabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccineo-logo-big.png"))); // NOI18N
        logolabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logolabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logolabel4MouseClicked(evt);
            }
        });

        ppllabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-nav.png"))); // NOI18N
        ppllabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ppllabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppllabel4MouseClicked(evt);
            }
        });

        logoutlabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-nav.png"))); // NOI18N
        logoutlabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutlabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navpanel4Layout = new javax.swing.GroupLayout(navpanel4);
        navpanel4.setLayout(navpanel4Layout);
        navpanel4Layout.setHorizontalGroup(
            navpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navpanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(logolabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 982, Short.MAX_VALUE)
                .addComponent(ppllabel4)
                .addGap(34, 34, 34)
                .addComponent(logoutlabel4)
                .addGap(117, 117, 117))
        );
        navpanel4Layout.setVerticalGroup(
            navpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navpanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logolabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(navpanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(navpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppllabel4)
                    .addComponent(logoutlabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        logopanel.setBackground(new java.awt.Color(237, 246, 249));
        logopanel.setPreferredSize(new java.awt.Dimension(228, 86));

        javax.swing.GroupLayout logopanelLayout = new javax.swing.GroupLayout(logopanel);
        logopanel.setLayout(logopanelLayout);
        logopanelLayout.setHorizontalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        logopanelLayout.setVerticalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbutton.setForeground(new java.awt.Color(0, 109, 119));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.png"))); // NOI18N
        backbutton.setText("Back ");
        backbutton.setBorderPainted(false);
        backbutton.setContentAreaFilled(false);
        backbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbutton.setFocusPainted(false);
        backbutton.setIconTextGap(15);
        backbutton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(237, 246, 249));
        jPanel2.setPreferredSize(new java.awt.Dimension(1240, 95));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 149, 120));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Let's protect yourself and those around you by vaccinating");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/res-vaccine-logo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 149, 120));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Follow these simple steps to register.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(226, 149, 120));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" - Please ensure that all the information provided is complete and accurate for a smooth and");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(226, 149, 120));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("   fuss-free registration.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(237, 246, 249));
        jPanel3.setPreferredSize(new java.awt.Dimension(1240, 390));

        jLabel4.setBackground(new java.awt.Color(0, 109, 119));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 109, 119));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Name");

        nameLabelView.setBackground(new java.awt.Color(0, 109, 119));
        nameLabelView.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabelView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabelView.setText("Test");

        jLabel8.setBackground(new java.awt.Color(0, 109, 119));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 109, 119));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("IC / Passport");

        idLabelView.setBackground(new java.awt.Color(0, 109, 119));
        idLabelView.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLabelView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idLabelView.setText("Test");

        jLabel10.setBackground(new java.awt.Color(0, 109, 119));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 109, 119));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Choose your preferred vaccination centre.");

        chooseCentre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chooseCentre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chooseCentre.setPreferredSize(new java.awt.Dimension(289, 54));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(706, 1141, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(idLabelView)
                            .addComponent(jLabel8)
                            .addComponent(nameLabelView))
                        .addGap(0, 759, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabelView)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idLabelView)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(237, 246, 249));
        jPanel4.setPreferredSize(new java.awt.Dimension(1240, 390));

        jLabel11.setBackground(new java.awt.Color(0, 109, 119));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 109, 119));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("1. Are you interested to take the COVID-19 vaccine?");

        yes1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes1.setForeground(new java.awt.Color(0, 109, 119));
        yes1.setText("Yes");
        yes1.setContentAreaFilled(false);
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        no1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no1.setForeground(new java.awt.Color(0, 109, 119));
        no1.setText("No");
        no1.setContentAreaFilled(false);
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        no2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no2.setForeground(new java.awt.Color(0, 109, 119));
        no2.setText("No");
        no2.setContentAreaFilled(false);
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });

        yes2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes2.setForeground(new java.awt.Color(0, 109, 119));
        yes2.setText("Yes");
        yes2.setContentAreaFilled(false);
        yes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes2ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 109, 119));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 109, 119));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("2. Are you registered with the Department of Social Welfare Malaysia as a Disabled Person (OKU)?");

        jLabel13.setBackground(new java.awt.Color(0, 109, 119));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 109, 119));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("3. Have you attended any event / areas associated with known COVID-19 cluster? ");

        yes3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes3.setForeground(new java.awt.Color(0, 109, 119));
        yes3.setText("Yes");
        yes3.setContentAreaFilled(false);
        yes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes3ActionPerformed(evt);
            }
        });

        no3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no3.setForeground(new java.awt.Color(0, 109, 119));
        no3.setText("No");
        no3.setContentAreaFilled(false);
        no3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no3ActionPerformed(evt);
            }
        });

        no4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no4.setForeground(new java.awt.Color(0, 109, 119));
        no4.setText("No");
        no4.setContentAreaFilled(false);
        no4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ActionPerformed(evt);
            }
        });

        yes4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes4.setForeground(new java.awt.Color(0, 109, 119));
        yes4.setText("Yes");
        yes4.setContentAreaFilled(false);
        yes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes4ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 109, 119));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 109, 119));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("4. Have you travelled to any country outside Malaysia within 14 days before onset of symptoms?");

        jLabel15.setBackground(new java.awt.Color(0, 109, 119));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 109, 119));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("5. Have you had close contact to confirmed or suspected case of COVID-19 within 14 days before");

        no5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no5.setForeground(new java.awt.Color(0, 109, 119));
        no5.setText("No");
        no5.setContentAreaFilled(false);
        no5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ActionPerformed(evt);
            }
        });

        yes5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes5.setForeground(new java.awt.Color(0, 109, 119));
        yes5.setText("Yes");
        yes5.setContentAreaFilled(false);
        yes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes5ActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 109, 119));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 109, 119));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("onset of illness? ");

        no6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no6.setForeground(new java.awt.Color(0, 109, 119));
        no6.setText("No");
        no6.setContentAreaFilled(false);
        no6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ActionPerformed(evt);
            }
        });

        yes6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes6.setForeground(new java.awt.Color(0, 109, 119));
        yes6.setText("Yes");
        yes6.setContentAreaFilled(false);
        yes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes6ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 109, 119));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 109, 119));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("immunizations before?");

        jLabel18.setBackground(new java.awt.Color(0, 109, 119));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 109, 119));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("6. Experiencing severe side effects (such as seizures, fainting and hospitalization) after got any ");

        jLabel19.setBackground(new java.awt.Color(0, 109, 119));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 109, 119));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("7. Ever had a history of severe allergies? ");

        yes7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes7.setForeground(new java.awt.Color(0, 109, 119));
        yes7.setText("Yes");
        yes7.setContentAreaFilled(false);
        yes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes7ActionPerformed(evt);
            }
        });

        no7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no7.setForeground(new java.awt.Color(0, 109, 119));
        no7.setText("No");
        no7.setContentAreaFilled(false);
        no7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ActionPerformed(evt);
            }
        });

        no8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        no8.setForeground(new java.awt.Color(0, 109, 119));
        no8.setText("No");
        no8.setContentAreaFilled(false);
        no8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ActionPerformed(evt);
            }
        });

        yes8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yes8.setForeground(new java.awt.Color(0, 109, 119));
        yes8.setText("Yes");
        yes8.setContentAreaFilled(false);
        yes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes8ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(0, 109, 119));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 109, 119));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("8. Are you exhibiting 2 or more symptoms as listed below?");

        jLabel21.setBackground(new java.awt.Color(0, 109, 119));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 109, 119));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("- Fever ");

        jLabel22.setBackground(new java.awt.Color(0, 109, 119));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 109, 119));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("- Chills ");

        jLabel23.setBackground(new java.awt.Color(0, 109, 119));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 109, 119));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("- Shivering (rigor) ");

        jLabel24.setBackground(new java.awt.Color(0, 109, 119));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 109, 119));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("- Body ache ");

        jLabel25.setBackground(new java.awt.Color(0, 109, 119));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 109, 119));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("- Headache ");

        jLabel26.setBackground(new java.awt.Color(0, 109, 119));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 109, 119));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("- Sore throat ");

        jLabel27.setBackground(new java.awt.Color(0, 109, 119));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 109, 119));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("- Runny nose or nasal congestion ");

        jLabel28.setBackground(new java.awt.Color(0, 109, 119));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 109, 119));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("- Fatigue ");

        jLabel29.setBackground(new java.awt.Color(0, 109, 119));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 109, 119));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("- Diarhea");

        jLabel30.setBackground(new java.awt.Color(0, 109, 119));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 109, 119));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("- Nausea or vomiting");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(138, 40));

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitButton.setText("Submit");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cancelButton.setBackground(new java.awt.Color(0, 109, 119));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(226, 149, 120));
        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cancelButton))
                            .addComponent(no8)
                            .addComponent(yes8)
                            .addComponent(jLabel19)
                            .addComponent(no7)
                            .addComponent(yes7)
                            .addComponent(jLabel18)
                            .addComponent(no6)
                            .addComponent(yes6)
                            .addComponent(jLabel15)
                            .addComponent(no5)
                            .addComponent(yes5)
                            .addComponent(jLabel14)
                            .addComponent(no4)
                            .addComponent(yes4)
                            .addComponent(jLabel13)
                            .addComponent(no3)
                            .addComponent(yes3)
                            .addComponent(jLabel12)
                            .addComponent(no2)
                            .addComponent(yes2)
                            .addComponent(no1)
                            .addComponent(yes1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel24))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel27)))
                                .addComponent(jLabel20)))
                        .addGap(0, 149, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no1)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no2)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no3)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no4)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no5)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no6)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no7)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yes8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(no8)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout basepanel1Layout = new javax.swing.GroupLayout(basepanel1);
        basepanel1.setLayout(basepanel1Layout);
        basepanel1Layout.setHorizontalGroup(
            basepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(basepanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(basepanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(backbutton))
            .addGroup(basepanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(basepanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(basepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        basepanel1Layout.setVerticalGroup(
            basepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanel1Layout.createSequentialGroup()
                .addGroup(basepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basepanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logopanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(backbutton)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(basepanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logolabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logolabel4MouseClicked
        // TODO add your handling code here:
        String value = ppl.getId();
        PeopleDashboard ppldash = new PeopleDashboard();
        ppldash.peopleInfo(value);
        ppldash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logolabel4MouseClicked

    private void ppllabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppllabel4MouseClicked
        // TODO add your handling code here:
        String value = ppl.getId();
        Profile pro = new Profile();
        pro.peopleInfo(value);
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ppllabel4MouseClicked

    private void logoutlabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlabel4MouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Exit program",
                JOptionPane.ERROR_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            Login log = new Login();

            setVisible(false);
            log.setVisible(true);
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_logoutlabel4MouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        String value = ppl.getId();
        PeopleDashboard ppldash = new PeopleDashboard();
        ppldash.peopleInfo(value);
        ppldash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        String value = ppl.getId();
        PeopleDashboard ppldash = new PeopleDashboard();
        ppldash.peopleInfo(value);
        ppldash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        
        /*if role == "admin"*/
// TODO add your handling code here:
        String name = nameLabelView.getText();
        String id = idLabelView.getText();
        String centre = chooseCentre.getSelectedItem().toString();
        String q1 = null, q2 = null, q3 = null, q4 = null, q5 = null, q6 = null, q7 = null, q8 = null;

        if (yes1.isSelected()) {
            q1 = "yes";
        } else if (no1.isSelected()) {
            q1 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 1!");
        }

        if (yes2.isSelected()) {
            q2 = "yes";
        } else if (no2.isSelected()) {
            q2 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 2!");
        }

        if (yes3.isSelected()) {
            q3 = "yes";
        } else if (no3.isSelected()) {
            q3 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 3!");
        }

        if (yes4.isSelected()) {
            q4 = "yes";
        } else if (no4.isSelected()) {
            q4 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 4!");
        }

        if (yes5.isSelected()) {
            q5 = "yes";
        } else if (no5.isSelected()) {
            q5 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 5!");
        }

        if (yes6.isSelected()) {
            q6 = "yes";
        } else if (no6.isSelected()) {
            q6 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 6!");
        }

        if (yes7.isSelected()) {
            q7 = "yes";
        } else if (no7.isSelected()) {
            q7 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 7!");
        }

        if (yes8.isSelected()) {
            q8 = "yes";
        } else if (no8.isSelected()) {
            q8 = "no";
        } else {
            JOptionPane.showMessageDialog(null, "Please answer question 8!");
        }

        if (yes1.isSelected() || no1.isSelected()) {
            if (yes2.isSelected() || no2.isSelected()) {
                if (yes3.isSelected() || no3.isSelected()) {
                    if (yes4.isSelected() || no4.isSelected()) {
                        if (yes5.isSelected() || no5.isSelected()) {
                            if (yes6.isSelected() || no6.isSelected()) {
                                if (yes7.isSelected() || no7.isSelected()) {
                                    if (yes8.isSelected() || no8.isSelected()) {
                                        try {
                                            String newVacStatus = "Pending 1st Dose";
                                            ppl.peopleDeclaration(name, id, q1, q2, q3, q4, q5, q6, q7, q8);
                                            app.registerForVaccination(id, centre);
                                            ppl.updateNewStatus(id, newVacStatus);
                                            this.setVisible(false);
                                            String value = ppl.getId();
                                            PeopleDashboard ppldash = new PeopleDashboard();
                                            ppldash.peopleInfo(value);
                                            ppldash.setVisible(true);
                                            this.setVisible(false);
                                        } catch (Exception e) {
                                            JOptionPane.showMessageDialog(null, "Failed to register for vaccination.");
                                        }
                                    }
                                }
                            }
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_submitButtonMouseClicked

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        // TODO add your handling code here:
        if (yes1.isSelected()) {
            no1.setSelected(false);
        }
    }//GEN-LAST:event_yes1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
        if (no1.isSelected()) {
            yes1.setSelected(false);
        }
    }//GEN-LAST:event_no1ActionPerformed

    private void yes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes2ActionPerformed
        // TODO add your handling code here:
        if (yes2.isSelected()) {
            no2.setSelected(false);
        }
    }//GEN-LAST:event_yes2ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
        // TODO add your handling code here:
        if (no2.isSelected()) {
            yes2.setSelected(false);
        }
    }//GEN-LAST:event_no2ActionPerformed

    private void yes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes3ActionPerformed
        // TODO add your handling code here:
        if (yes3.isSelected()) {
            no3.setSelected(false);
        }
    }//GEN-LAST:event_yes3ActionPerformed

    private void no3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no3ActionPerformed
        // TODO add your handling code here:
        if (no3.isSelected()) {
            yes3.setSelected(false);
        }
    }//GEN-LAST:event_no3ActionPerformed

    private void yes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes4ActionPerformed
        // TODO add your handling code here:
        if (yes4.isSelected()) {
            no4.setSelected(false);
        }
    }//GEN-LAST:event_yes4ActionPerformed

    private void no4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no4ActionPerformed
        // TODO add your handling code here:
        if (no4.isSelected()) {
            yes4.setSelected(false);
        }
    }//GEN-LAST:event_no4ActionPerformed

    private void yes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes5ActionPerformed
        // TODO add your handling code here:
        if (yes5.isSelected()) {
            no5.setSelected(false);
        }
    }//GEN-LAST:event_yes5ActionPerformed

    private void no5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no5ActionPerformed
        // TODO add your handling code here:
        if (no5.isSelected()) {
            yes5.setSelected(false);
        }
    }//GEN-LAST:event_no5ActionPerformed

    private void yes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes6ActionPerformed
        // TODO add your handling code here:
        if (yes6.isSelected()) {
            no6.setSelected(false);
        }
    }//GEN-LAST:event_yes6ActionPerformed

    private void no6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no6ActionPerformed
        // TODO add your handling code here:
        if (no6.isSelected()) {
            yes6.setSelected(false);
        }
    }//GEN-LAST:event_no6ActionPerformed

    private void yes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes7ActionPerformed
        // TODO add your handling code here:
        if (yes7.isSelected()) {
            no7.setSelected(false);
        }
    }//GEN-LAST:event_yes7ActionPerformed

    private void no7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no7ActionPerformed
        // TODO add your handling code here:
        if (no7.isSelected()) {
            yes7.setSelected(false);
        }
    }//GEN-LAST:event_no7ActionPerformed

    private void yes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes8ActionPerformed
        // TODO add your handling code here:
        if (yes8.isSelected()) {
            no8.setSelected(false);
        }
    }//GEN-LAST:event_yes8ActionPerformed

    private void no8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no8ActionPerformed
        // TODO add your handling code here:
        if (no8.isSelected()) {
            yes8.setSelected(false);
        }
    }//GEN-LAST:event_no8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Object[] centreName = c.getAllCentreName();
            for (Object centre : centreName) {
                chooseCentre.addItem((String) centre);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegisterVaccine.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JPanel basepanel1;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JComboBox<String> chooseCentre;
    private javax.swing.JLabel idLabelView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logolabel4;
    private javax.swing.JPanel logopanel;
    private javax.swing.JLabel logoutlabel4;
    private javax.swing.JLabel nameLabelView;
    private javax.swing.JPanel navpanel4;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JRadioButton no3;
    private javax.swing.JRadioButton no4;
    private javax.swing.JRadioButton no5;
    private javax.swing.JRadioButton no6;
    private javax.swing.JRadioButton no7;
    private javax.swing.JRadioButton no8;
    private javax.swing.JLabel ppllabel4;
    private javax.swing.JLabel submitButton;
    private javax.swing.JRadioButton yes1;
    private javax.swing.JRadioButton yes2;
    private javax.swing.JRadioButton yes3;
    private javax.swing.JRadioButton yes4;
    private javax.swing.JRadioButton yes5;
    private javax.swing.JRadioButton yes6;
    private javax.swing.JRadioButton yes7;
    private javax.swing.JRadioButton yes8;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
